default:
  ipfs:
    api: /ip4/127.0.0.1/tcp/5001
    enable-eth: true
  eth:
    datadir: ~/.geth
    api: http://localhost:8545
    event-offset: 100

development:
  eth:
    datadir: /mnt/u110/ethereum/pnet1
    account: '0x7116673528278887d37038d93bd749b66110ec35'
    password: dlheu0
    mother-contract: '0x8bdfcef3d5ec77a77985d07925b05e5f9302b9a8'

test:

production:
